### ISSUE TITLE
Parallelization of Existing Code

### ISSUE THREAD

**Issue by terrytangyuan** [all-umass/metric-learn#10]
@perimosocordiae Do you think it is hard/necessary to parallelize the existing code, in particular those for those `for loops`? In other words, make the multi-thread/multi-core versions, in cases where each iteration is independent so that this can better deal with larger data set?

**Comment by perimosocordiae** [comment]
The easiest performance improvement will probably be writing the hot loops in Cython. Once that's done, we can figure out where parallelization would be useful.
