### ISSUE TITLE
Error when impostors list is empty

### ISSUE THREAD

**Issue by varunagrawal** [all-umass/metric-learn#17]
Numpy throws an error in np.hstack(impostors) when impostors is empty.
What would be the recommended way to fix this?

**Comment by perimosocordiae** [comment]
If the impostors list is empty, the rest of the algorithm doesn't make much sense to run. That being said, the code should handle that case more gracefully. A simple check before calling `hstack` could avoid the error, but the main `fit()` function should handle the lack of impostors in some way as well.

**Comment by varunagrawal** [comment]
Exactly! If a particular dataset happens to provide no impostors, shouldn't the code just display the appropriate nearest neighbors?

**Comment by varunagrawal** [comment]
Hi,
Still waiting for a suggestion on the fix. I can work on the PR once I get the suggestion.

**Comment by perimosocordiae** [comment]
Sorry for the late response. In [the `fit` method](https://github.com/all-umass/metric-learn/blob/master/metric_learn/lmnn.py#L63), we could check the size of `impostors` and raise a warning if it's empty. At that point, it probably makes sense to return early.

**Comment by anirudt** [comment]
@perimosocordiae : Return early with the linear transformation as an identity matrix, i.e. do nothing, right?

**Comment by perimosocordiae** [comment]
Yep, that makes sense.
