### ISSUE TITLE
Shogun LMNN MulticlassLabels type error

### ISSUE THREAD

**Issue by GMNGeoffrey** [all-umass/metric-learn#2]
I'm trying to get the LMNN working with the shogun C++ implementation. I previously had things running with the python LMNN, but it was very slow for my dataset and I was hoping to speed things up. I got shogun installed with the python modular, but when I try to do a fit on an LMNN instance I get the following error:

File "build/bdist.linux-x86_64/egg/metric_learn/lmnn.py", line 240, in fit
NotImplementedError: Wrong number or type of arguments for overloaded function 'new_MulticlassLabels'.
  Possible C/C++ prototypes are:
    shogun::CMulticlassLabels::CMulticlassLabels()
    shogun::CMulticlassLabels::CMulticlassLabels(int32_t)
    shogun::CMulticlassLabels::CMulticlassLabels(shogun::SGVector< float64_t >)
    shogun::CMulticlassLabels::CMulticlassLabels(shogun::CFile *)

Line 240 of lmnn.py is
      labels = MulticlassLabels(labels.astype(np.float64))

so it looks like this isn't coercing the class labels to the correct datatype of SGVector< float64_t >. I checked to make sure my classes could be successfully coerced with astype(np.float_64), so that's not the problem. Not sure how to proceed to get this working. Any help would be most appreciated.

**Comment by perimosocordiae** [comment]
Hmm, that's interesting. I'll try to reproduce the issue on my end. What version of shogun are you using?

**Comment by GMNGeoffrey** [comment]
3.1.1 I think, which now that I'm looking at the website seems to be not the latest version. Not sure how I ended up with an old version since I just installed it the other day. I'll also try the latest version to see if that fixes things.

**Comment by perimosocordiae** [comment]
Any news?

**Comment by GMNGeoffrey** [comment]
Hey sorry I completely vanished on this. I was working on a project for a class and then the project ended, so I never ended up trying to install a new version of Shogun. I'm using LMNN again though and with a fresh install of Shogun 4.1, it's using the Shogun correctly!

**Comment by MrDarcy1** [comment]
`      self.X_, y = check_X_y(X, y, dtype=float)
      labels = MulticlassLabels(y.astype(np.float64))
      self._lmnn = shogun_LMNN(RealFeatures(self.X_.T), labels, self.k)`

`NotImplementedError: Wrong number or type of arguments for overloaded function 'new_RealFeatures'.
  Possible C/C++ prototypes are:
    shogun::CDenseFeatures< float64_t >::CDenseFeatures(int32_t)
    shogun::CDenseFeatures< float64_t >::CDenseFeatures()
    shogun::CDenseFeatures< float64_t >::CDenseFeatures(shogun::CDenseFeatures< float64_t > const &)
    shogun::CDenseFeatures< float64_t >::CDenseFeatures(shogun::SGMatrix< double >)
    shogun::CDenseFeatures< float64_t >::CDenseFeatures(shogun::CFile *)`

I also met this problem with the newest shogun 6.1.3. Should I download 4.1 and how?
