### ISSUE TITLE
fit_transform doesn't exist for Covariance

### ISSUE THREAD

**Issue by bhargavvader** [all-umass/metric-learn#24]
The code snippet [here](https://all-umass.github.io/metric-learn/metric_learn.covariance.html) in the docs mention using `cos.fit_transform`, but the Covariance class only has `fit`. Should the docs be changed, or am I interpreting something wrong here? 

And if we're intending to apply the transformation, how do we do it?

**Comment by perimosocordiae** [comment]
Good catch. `fit_transform` is a common method in scikit-learn, but we don't define it here yet. I updated the example in the docs.
