### ISSUE TITLE
transform() method for the shogun_LMNN

### ISSUE THREAD

**Issue by anirudt** [all-umass/metric-learn#29]
Going by the current implementation, it lacks a transform() and metric() for the Shogun wrapping implementation of the LMNN.

In case it is required / Unless someone is currently working on it, I would like to work on it.

Open to suggestions!

**Comment by perimosocordiae** [comment]
Both the shogun and pure Python implementations of LMNN use the `BaseMetricLearner` (superclass) implementation of `transform()` and `metric()`, so no action is required here.

**Comment by anirudt** [comment]
My apologies, didn't notice that! Is there a nice point for me to start contributing to the community? :)

**Comment by perimosocordiae** [comment]
The algorithm wish list (#13) is a good place to start! :+1:
