### ISSUE TITLE
X - size limits 

### ISSUE THREAD

**Issue by mglowacki100** [all-umass/metric-learn#31]
I've tried to used library with following data X:
- 20 features
- 65k data-points

and I got with **fit** function following error:
IndexError: indices are out-of-bounds
I use pandas to load data and basic preprocessing like dropping 'target'.

Are there any internal limits in size of X?

**Comment by perimosocordiae** [comment]
It's hard to say what the problem is without more information, but one possibility is that you're passing in a pandas object rather than a numpy array. This library wasn't designed to work with pandas objects.

**Comment by mglowacki100** [comment]
I've changed load method from pandas to numpy genfromtxt. It seems to work now, but it is very greedy for RAM - 64gb is not enough. I'll try with swap file.
Do you have any estimates, what amount of RAM is more or less required for csv as stated above?

**Comment by perimosocordiae** [comment]
It really depends on the specific method you're using, because some of the implementations in this library haven't been optimized for memory usage yet.

Algorithmic limitations may also come into play: some methods construct an n by n matrix internally, which in your case would take about 34 GB just to store in memory.

**Comment by mglowacki100** [comment]
I think we can close this issue, but it would be nice to have info about memory-consumption for specific methods in documentation.

**Comment by mglowacki100** [comment]
I've changed  dataframe from panda to numpy array, and now everything works correctly, except that ITML, LFDA and NCA requires large swapfile for my data.
I think it would be nice to add strong warning in documentation that pandas is not recommended.
