### ISSUE TITLE
Constraints in the form of similar and dissimilar sets

### ISSUE THREAD

**Issue by bhargavvader** [all-umass/metric-learn#40]
I wanted to know if any of the metric-learning algorithms implemented accept the supervision in the form of sets which are similar and dissimilar. For example in Xing's seminal work on metric learning ([paper](http://ai.stanford.edu/%7Eang/papers/nips02-metric.pdf)), the constraints are two sets, S (similar vectors), and D (dissimilar vectors). Even in ITML, it's the same terminology.

Is the current way of using D(a,b) > D(c,d) just another way of doing this? I can imagine it would be, but I want to make sure.

Also wanted to know if any of the algorithms currently implemented can be thought of as non-linear metric learning - and if none are, if there are any plans to add a non-linear metric learning algorithm.

Thanks for taking the time to answer this!

**Comment by bhargavvader** [comment]
I feel quite silly now, it's quite clear that the `D(X[a],X[b]) < D(X[c],X[d])` is pretty much similar and dissimilar sets. :)

Will close this issue the moment I get any head's up on non-linear metric learning!

**Comment by bhargavvader** [comment]
ping @perimosocordiae

**Comment by perimosocordiae** [comment]
All of the algorithms currently implemented are linear, as they all provide a Mahalanobis-like matrix via `metric()` and the associated linear transformation via `transformer()`.

Nonlinear metric learning is a bit more vague; would this include dimensionality reduction / embedding methods? If there are good nonlinear methods in the literature that don't fit elsewhere, I'm happy to include them here.

**Comment by bhargavvader** [comment]
I found [this](https://arxiv.org/pdf/1306.6709.pdf) survey giving nice examples of non-linear metric learning. 

But thanks for answering my query: I'm closing the issue!
