### ISSUE TITLE
RCA - Non-invertible inner covariance matrix 

### ISSUE THREAD

**Issue by ab-anssi** [all-umass/metric-learn#49]
The current implementation of RCA does not check whether the inner covariance matrix is invertible. However, when this matrix is not invertible, it has some null eigen values, and so the transformation matrix `transformer_` contains Nan values. 
I provide an example illustrating this problem. [rca_non_invertible_covariance.txt](https://github.com/all-umass/metric-learn/files/738990/rca_non_invertible_covariance.txt)

The solution is to select only eigenvalues that are NOT NULL.
There is a problem when the rank of the inner covariance matrix, denoted by `r`, is smaller than `dim`, the number of dimension requested. I think a good solution is to return a matrix with `r` dimensions, and to display a warning to the user.

What do you think of this bug fix ? Can I send a pull request ?

**Comment by perimosocordiae** [comment]
I like your proposed solution, and I look forward to the pull request! 👍

**Comment by perimosocordiae** [comment]
Closed by #50.
