### ISSUE TITLE
error on running LFDA algorithm

### ISSUE THREAD

**Issue by a367** [all-umass/metric-learn#54]
hi, I want to use LFDA algorithm for my data but have some confused problem.
firstly, I try the example code in the document, every thing is ok. but when I run this for myself data, It got an error:
```
  File "unit_test.py", line 245, in person_reid_LFDA
    lfda.fit(train_X, train_Y)
  File "/usr/local/lib/python2.7/dist-packages/metric_learn/lfda.py", line 105, in fit
    which='LA')
  File "/usr/local/lib/python2.7/dist-packages/scipy/sparse/linalg/eigen/arpack/arpack.py", line 1605, in eigsh
    params.iterate()
  File "/usr/local/lib/python2.7/dist-packages/scipy/sparse/linalg/eigen/arpack/arpack.py", line 537, in iterate
    self.ipntr, self.workd, self.workl, self.info)
ValueError: On entry to DLASCL parameter number 4 had an illegal value
```
in this case, train_X shape is (632, 4096), train_Y shape is (632,), and my code is:
```
    lfda = LFDA(k=5, dim=128)
    lfda.fit(train_X, train_Y)
```
Is there any idea for this error?

**Comment by perimosocordiae** [comment]
Looks like you might have an issue with your scipy installation. What dtypes are `train_X` and `train_Y`?

**Comment by a367** [comment]
@perimosocordiae Thanks for your reply! but I'm sure that  train_X and train_Y dtype are both "float32", which should not cause the error.

I think I find the problem, the latest version in pip installation  is 0.3.0, but code in here is 0.4.0. I install the 0.4.0 code and It can work well. I think [line 142](https://github.com/all-umass/metric-learn/blob/master/metric_learn/lfda.py#L142) figure out the ValueError in my case.

But when I want to use the lfda.metric() to get the metric matrix, I get a new error, which seems to think that **lfda.metric is a str type**.I review the code in [line 51](https://github.com/all-umass/metric-learn/blob/master/metric_learn/lfda.py#L51), I think this is a bug.

when I replace the "metric" to "_metric", I find that It will raise another confused error:
```
File "/usr/lib/python2.7/dist-packages/sklearn/base.py", line 141, in _pprint
    this_repr = '%s=%s' % (k, printer(v))
  File "/usr/lib/python2.7/dist-packages/sklearn/base.py", line 277, in __repr__
    offset=len(class_name),),)
```
I try several different sense, when I don't do the replacement, in other words, let
```
self.metric = metric # metric is a str
``` 
every thing is OK except can't get the metric matrix. 

when I do the replace, commit [line 131](https://github.com/all-umass/metric-learn/blob/master/metric_learn/lfda.py#L131), then it works well, I can get the metric matrix by calling the `lfda.metric()`

**Comment by perimosocordiae** [comment]
You're right, this is a bug! It was triggered by the recent efforts to make things more sklearn-compatible, and somehow wasn't caught by the unit tests.

Until a fix is submitted, one workaround is to use the `transformer()` method and create the metric matrix yourself, in the same way the base class does it: https://github.com/all-umass/metric-learn/blob/238be72c00fde4f4351601ef1ce8c2fcd710c9e3/metric_learn/base_metric.py#L19
