### ISSUE TITLE
Inconsistent conversion between transformer and metric

### ISSUE THREAD

**Issue by Callidior** [all-umass/metric-learn#57]
According to the documentation, the learned distance between `x` and `y` is expressed as `sqrt((x-y).dot(inv(M)).dot(x-y))`, which is equivalent to evaluating the Euclidean distance in the transformed space obtained from `dot(X, L.T)` for `n x d` data matrices `X` with `L = inv(cholesky(M))`.

However, if an algorithm does not learn a metric `M`, but its corresponding transformer `L` directly, the current implementation of `BaseMetricLearner.metric()` computes `M` as `L.T.dot(L)`, which actually equals `inv(M)`, according to the definition of `L` given above.

If I got the documentation right, then the following *should* hold:

    learner.transformer().T.dot(learner.transformer()) == learner.metric()

This is, however, currently not the case for algorithms learning `M` (e.g., ITML, LSML or even the covariance method).

----

In addition, the definition of a "metric" is not even consistent across different learners: ITML and LSML learn a metric `sqrt((x-y).dot(M).dot(x-y))`, while the covariance method and SDLM (I guess) use `inv(M)` as stated in the readme.

Thus, **the transformers returned by ITML and LSML are wrong!**

I would suggest harmonizing the terminology towards the one currently employed by ITML and LSML, since it seems also predominant in literature, in my opinion. This would require removing the `inv()` from `BaseMetricLearner.transformer()` as well as changing all learners relying on the current terminology, such as ITML ans LSML.

**Comment by perimosocordiae** [comment]
Thanks for bringing this issue up. I agree that we need to be more consistent with the mapping between transformers and metrics.

I want to make sure we get this right, so I'm going to re-read some of the literature and see if I come to the same conclusion you did.

**Comment by Callidior** [comment]
Thanks for looking into this!
I completely agree that a change like this needs to be made very carefully.

Just in case you come to the same conclusion as I, I've already tried to make the necessary changes in the Pull Request referenced above.
Since ITML and LSML return just wrong transformers at the moment, their performance could be significantly improved by fixing this issue.

**Comment by perimosocordiae** [comment]
After letting this languish for too long, I think I'm convinced. Thanks for pointing this out!
