### ISSUE TITLE
Train from pairs not label

### ISSUE THREAD

**Issue by andreydung** [all-umass/metric-learn#63]
Is it possible to train metric from a list of pairs (similar and dissimilar)? My groundtruth consists of these pairs and thus can't use label.

**Comment by Callidior** [comment]
It depends on the algorithm. In case of LSML, ITML, and SDML, this is possible using the classes named `LSML`, `ITML`, and `SDML`, respectively, whose `fit()` method takes pairwise constraints or connectivity graphs as arguments. The classes `LSML_Supervised`, `ITML_Supervised`, and `SDML_Supervised` are merely wrappers around those, generating pair-wise similarity and dissimilarity constraints from class labels.
