### ISSUE TITLE
Cannot Load MLKR & MMC, everything else is fine

### ISSUE THREAD

**Issue by bscully** [all-umass/metric-learn#76]
python2.7 64bit, windows7
metric_learn v 0.3.0

This does not work for me:
   from metric_learn import *
   mod = MLKR()

error:
NameError: name 'MLKR' is not defined

Any ideas?

**Comment by perimosocordiae** [comment]
MLKR and MMC are new since version 0.3.0.

I hope to release v0.4 sometime soon, but until then you can try upgrading to the version currently on the master branch:
`pip install https://github.com/all-umass/metric-learn/archive/master.zip`
