### ISSUE TITLE
MMC - fit_diag can potentially loop forever

### ISSUE THREAD

**Issue by shalan12** [all-umass/metric-learn#79]
For the condition in the while loop in MMC - fit_diag
`while error > self.convergence_threshold: `

I think the number of iterations should also be checked here. I've had runs where it keeps running and getting the same value for `conv`. It doesn't respect `max_iter`, and doesn't terminate.

**Comment by perimosocordiae** [comment]
I agree, the `_fit_diag` method should respect `max_iter`. Feel free to open a PR if you'd like to fix it!

**Comment by perimosocordiae** [comment]
Fixed by gh-80.
