### ISSUE TITLE
Documentation on the package

### ISSUE THREAD

**Issue by terrytangyuan** [all-umass/metric-learn#8]
@perimosocordiae  I am thinking we should write some documentation for the usages or intro to some algorithms(maybe some links to papers to save time). I am suggesting using [Sphinx](http://sphinx-doc.org/rest.html) and following the [Numpy Docstring Standard](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt). What do you think? 

Interestingly, the [dml R package](https://github.com/terrytangyuan/dml) that I wrote covers mostly the not-yet-implemented algorithms in `metric-learn`. It'll probably take me some time to understand each implemented algorithms though. 

If you think this is necessary, I can start doing it during my free time.

**Comment by perimosocordiae** [comment]
I think those are good choices. The API surface is fairly small, so hopefully there won't be too many docs to write.

**Comment by perimosocordiae** [comment]
We now have html docs on github pages!

http://all-umass.github.io/metric-learn/

**Comment by terrytangyuan** [comment]
It looks so great! Good job!
