### ISSUE TITLE
LMNN - performance with shogun 6.1.3

### ISSUE THREAD

**Issue by laurazh** [all-umass/metric-learn#81]
I try the metric-learn library and it is said that if 

>  a recent version of the Shogun Python modular (modshogun) library is available, the LMNN implementation will use the fast C++ version from there

 I installed the shogun 6.1.3 with conda.

 I saw in the code that you try to `import modshogun` but with the shogun 6.1.3, the import is ` import shogun `. 

I  was wondering, if it will still use shogun or if it will use the pure python code.

I have not notice any change in the performance in time for my case.

**Comment by perimosocordiae** [comment]
Looks like they may have made some changes to shogun. As things stand now, if the `import modshogun` line fails, the pure Python fallback implementation is used.

Can you try changing the import in your install of metric-learn and let me know how it goes?
